version: "3.9"

services:
    db:
        image: mysql:8.0.33
        restart: always
        ports:
            - 3306
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_DATABASE: dzencode

    app:
        build:
            context: ..
            dockerfile: "./docker/app.Dockerfile"
        restart: always
        ports:
            - "3001:3000"
        depends_on:
            - db
        environment:
            DATABASE_URL: "mysql://root@db/dzencode"
            JWT_COOKIE_DOMAIN: localhost
            JWT_SECRET: secretdontreadit
