version: "3.3"

services:
    db:
        image: mysql:8.0.33
        restart: always
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: dzencode
        ports:
            - 3306

    app:
        build:
            context: ..
            dockerfile: ./docker/app.Dockerfile
        restart: always
        depends_on:
            - db
        environment:
            PORT: 3001
            DATABASE_URL: "mysql://root@db/dzencode"
        ports:
            - 3001
        env_file:
            - .env

    nginx:
        build:
            context: .
            dockerfile: ./nginx.Dockerfile
        restart: always
        ports:
            - ${NGINX_PORT:-443}:443
        depends_on:
            - app
