version: "3.9"

services:
    db:
        image: mysql:8.0.33
        restart: always
        ports:
            - "3307:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_DATABASE: dzencode
