version: "3.3"

services:
    db:
        extends:
            file: ./common-services.yml
            service: db
        ports:
            - 3306

    app:
        extends:
            file: ./common-services.yml
            service: app
        ports:
            - 3001
        env_file:
            - .env

    nginx:
        build:
            context: .
            dockerfile: ./nginx.Dockerfile
        restart: always
        ports:
            - ${NGINX_PORT:-443}:443
        depends_on:
            - app
